package com.exception;

public class TestError {
	public static void main(String[] args) {
		try {

		} catch (Error e) {
			System.out.println("");
		}
	}
}
